export enum RoleType {
  OWNER = 'OWNER',
  SHOP_MANAGER = 'SHOP_MANAGER',
  COLLECTION_AGENT = 'COLLECTION_AGENT',
  CUSTOMER = 'CUSTOMER',
}

export enum OrderStatus {
  DRAFT = 'DRAFT',
  CONFIRMED = 'CONFIRMED',
  PROCESSING = 'PROCESSING',
  READY = 'READY',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  PARTIALLY_RETURNED = 'PARTIALLY_RETURNED',
  RETURNED = 'RETURNED',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PARTIAL = 'PARTIAL',
  PAID = 'PAID',
  OVERPAID = 'OVERPAID',
  REFUNDED = 'REFUNDED',
}

export enum PaymentMode {
  CASH = 'CASH',
  UPI = 'UPI',
  BANK_TRANSFER = 'BANK_TRANSFER',
  CHEQUE = 'CHEQUE',
  ONLINE_GATEWAY = 'ONLINE_GATEWAY',
  CREDIT_NOTE = 'CREDIT_NOTE',
}

export enum TransactionType {
  OPENING_BALANCE = 'OPENING_BALANCE',
  SALE_CREDIT = 'SALE_CREDIT',
  PAYMENT = 'PAYMENT',
  REFUND = 'REFUND',
  RETURN_CREDIT = 'RETURN_CREDIT',
  DISCOUNT_ADJUSTMENT = 'DISCOUNT_ADJUSTMENT',
  BAD_DEBT_WRITEOFF = 'BAD_DEBT_WRITEOFF',
  MANUAL_ADJUSTMENT = 'MANUAL_ADJUSTMENT',
  REVERSAL = 'REVERSAL',
}

export enum CollectionCycleStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  CLOSED = 'CLOSED',
  ARCHIVED = 'ARCHIVED',
}

export enum CollectionEntryStatus {
  PENDING = 'PENDING',
  PROMISED = 'PROMISED',
  PARTIALLY_COLLECTED = 'PARTIALLY_COLLECTED',
  COLLECTED = 'COLLECTED',
  SKIPPED = 'SKIPPED',
  UNREACHABLE = 'UNREACHABLE',
}
